version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  back-tier:
  docker_lan:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.25.2
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - ping:ping
      - speedtest:speedtest
      - mikrotik_exporter:mikrotik_exporter
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3030:3000
    networks:
      back-tier:
      docker_lan:
        ipv4_address: 192.168.10.40
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.internet-monitor.rule=Host(`internet-monitor.docker`)'
      - 'traefik.http.routers.internet-monitor.entrypoints=web'
      - 'traefik.http.services.internet-monitor.loadbalancer.server.port=3000'
      - "traefik.docker.network=docker_lan"

  ping:
    tty: true
    stdin_open: true
    expose:
      - 9115
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    restart: always
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier

  speedtest:
    tty: true
    stdin_open: true
    expose:
      - 9798
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always
    networks:
      - back-tier

  nodeexp:
    privileged: true
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier

  mikrotik_exporter:
    image: nshttpd/mikrotik-exporter:1.0.11 # replace version for latest version
    volumes:
      - './mikrotik-exporter/config:/config'
    env_file: ./mikrotik-exporter/env
    ports:
      - 9436:9436
    restart: always
    networks:
      - back-tier